version: '3'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8000:80"  
    volumes:
      - ./inventa:/var/www/html  
    depends_on:
      - mysqldb
    restart: always
    networks:
      - app-network
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8080:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysqldb
        - MYSQL_ROOT_PASSWORD=root
    restart: always
    depends_on:
        - mysqldb
    networks:
      - app-network
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
        - MYSQL_DATABASE=inventa
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
    ports:
        - "8989:3306" 
    volumes:
        - "./data/mysql:/var/lib/mysql"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge